language: php

php:
  - 5.5

install:
  - pear channel-discover pear.cakephp.org
  - pear install cakephp/CakePHP_CodeSniffer
  - phpenv rehash

script:
  - phpcs -n --standard=CakePHP app/Controller
  - phpcs -n --standard=CakePHP app/Model
